import { useState } from 'react'
import { saveReport } from '../firebase'
import { DIMENSIONS } from '../constants'
import { diagText } from '../utils'

export default function EmailModal({ score, url, results, specimenId, dateStr, onClose }) {
  const [email, setEmail] = useState(() => localStorage.getItem("bare_email") || "");
  const [status, setStatus] = useState("idle");

  const generateReportText = () => {
    const diag = diagText(score).join(" ");
    const divider = "\u2500".repeat(38);
    const assays = DIMENSIONS.map((d, i) => {
      const r = results[d.key];
      if (!r) return "";
      return [
        String(i + 1).padStart(2, "0") + ". " + d.label + " \u2014 " + r.score + "/100",
        '   "' + r.verdict + '"',
        "   RX \u2192 " + r.improvement,
        r.flags && r.flags.length ? "   FLAGS: " + r.flags.join(", ") : "",
      ].filter(Boolean).join("\n");
    }).join("\n\n");

    return [
      "BARE BRAND AUDIT REPORT",
      divider,
      "",
      "File:    #" + specimenId,
      "Date:    " + dateStr,
      "Subject: " + (url || "Image specimen"),
      "",
      "BARE SCORE: " + score + "/100",
      diag,
      "",
      "ASSAY BREAKDOWN",
      divider,
      "",
      assays,
      "",
      divider,
      "Generated by BARE \u00b7 Brand Aesthetic Reality Engine",
    ].join("\n");
  };

  const handleSend = async () => {
    if (!email.includes("@")) return;
    localStorage.setItem("bare_email", email);
    setStatus("sending");

    const reportText = generateReportText();
    const subject = encodeURIComponent("BARE Report #" + specimenId + " \u2014 Score " + score + "/100");
    const body = encodeURIComponent(reportText);
    window.open("mailto:" + encodeURIComponent(email) + "?subject=" + subject + "&body=" + body, "_blank");

    await saveReport({ email, score, url: url || "image", results, specimenId, dateStr });
    setStatus("done");
  };

  return (
    <div className="modal-overlay">
      <div className="modal-box">
        {status === "done" ? (
          <>
            <div className="eyebrow">/ REPORT SENT</div>
            <div className="modal-title">
              Check your inbox.<br/>
              <em style={{ color: "var(--accent)", fontStyle: "normal" }}>No flattery included.</em>
            </div>
            <button className="run-btn" onClick={onClose} style={{ marginTop: 0 }}>
              Done <span className="arrow">✓</span>
            </button>
          </>
        ) : (
          <>
            <div className="eyebrow">/ REPORT DELIVERY</div>
            <div className="modal-title">
              Score: <em style={{ color: "var(--accent)", fontStyle: "normal" }}>{score}</em>/100.<br/>
              Get the full receipts.
            </div>
            <div className="field" style={{ marginBottom: 20 }}>
              <div className="field-label">/ Your Email</div>
              <input
                className="bare-input"
                type="email"
                placeholder="your@email.com"
                value={email}
                onChange={e => setEmail(e.target.value)}
                onKeyDown={e => e.key === "Enter" && handleSend()}
                autoFocus
              />
            </div>
            <button
              className="run-btn"
              style={{ marginTop: 0 }}
              disabled={status === "sending" || !email.includes("@")}
              onClick={handleSend}
            >
              {status === "sending" ? "Opening email…" : "Send Report"}
              <span className="arrow">→</span>
            </button>
            <button className="modal-skip" onClick={onClose}>SKIP →</button>
          </>
        )}
      </div>
    </div>
  );
}
